# Freebox service entries description.

reboot:
  name: Reboot
  description: Reboots the Freebox.

flip:
  description: Flip the camera image.
  fields:
    entity_id:
      description: Entity id.
      example: "camera.living_room"
